app = "maturidade-ti-backend"

[build]
  dockerfile = "Dockerfile"

[env]
  SPRING_PROFILES_ACTIVE = "prod"
  JAVA_TOOL_OPTIONS = "-Djava.net.preferIPv4Stack=true"
  JAVA_OPTS = "-Djava.net.preferIPv4Stack=true"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]
